version: '3'

networks:
  app-tier:
    driver: bridge
  consul-demo:

services:
  app:
    build: .
    env_file:
      - .env
    container_name: devblog
    image: devblog:latest
    networks:
      - app-tier
    ports:
      - "443:443"
  redis:
    image: 'bitnami/redis:latest'
    container_name: ddd_cache
    env_file:
      - .env
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - REDIS_PASSWORD=$redis_pass
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - app-tier
  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - app-tier
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"


volumes:
  redis_data:
    driver: local
