# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master,feature/*,develop]
  pull_request:
    branches: [ master,develop ]
jobs:
  deployservers:
     runs-on: ubuntu-latest
     steps:
        - name: HashiCorp - Setup Terraform
          uses: hashicorp/setup-terraform@v1.0.1
        - name: Checkout source code
          uses: actions/checkout@master
        - name: Cache node modules0
          uses: actions/cache@v1
          with:
            path: node_modules
            key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.OS }}-build-
              ${{ runner.OS }}-
        - name: install
          run: sudo npm i -g yarn
        - name: Build
          run: yarn build
        - name: 'Terraform Init'
          run: terraform init
        - name: 'Terraform Plan'
          run: terraform plan

